name: Spring Petclinic CI with SonarQube

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test-sonarqube:
    name: Build, Test and SonarQube Scan
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

     
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
          PATH: /usr/lib/jvm/java-21-openjdk-amd64/bin:${{ env.PATH }}
        run: sonar-scanner